[metadata.heroku]
  root-package = "github.com/heroku/go-getting-started"
  go-version = "1.10"
  install = [ "./..." ]

required = ["github.com/jteeuwen/go-bindata"]

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/graph-gophers/graphql-go"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/nicksrandall/dataloader.v5"
  version = "5.0.0"

[prune]
  go-tests = true
  unused-packages = true
